# Site settings
title: 张明远
email: zmy112334@163.com
description: > # this means to ignore newlines until "baseurl:"
  西安西电机电学院(2011-2014)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://zmy1123347389.github.io/" # the base hostname & protocol for your site

oschina_username: zmy112334
csdn_username: zmy112334
github_username:  zmy1123347389
moble: 13521306775
・
# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""

#codehighlighter
